#line 2 "scriptc_compiler.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <istream>
#include <ostream>
#include <iostream>
using namespace std;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
static yyconst short int yy_acclist[362] =
    {   0,
       43,   43,   47,   47,   50,   50,   54,   54,  102,  100,
      101,    1,  100,  101,    3,  101,    2,  100,  101,   87,
      100,  101,  100,  101,   49,  100,  101,   93,  100,  101,
       86,  100,  101,  100,  101,   81,  100,  101,   82,  100,
      101,   91,  100,  101,   90,  100,  101,   79,  100,  101,
       89,  100,  101,   85,  100,  101,   92,  100,  101,   36,
      100,  101,   36,  100,  101,   98,  100,  101,   76,  100,
      101,   94,  100,  101,   80,  100,  101,   95,  100,  101,
       99,  100,  101,   52,  100,  101,   35,  100,  101,   83,
      100,  101,   84,  100,  101,   96,  100,  101,   35,  100,

      101,   35,  100,  101,   35,  100,  101,   35,  100,  101,
       35,  100,  101,   35,  100,  101,   35,  100,  101,   35,
      100,  101,   35,  100,  101,   35,  100,  101,   35,  100,
      101,   35,  100,  101,   35,  100,  101,   35,  100,  101,
       35,  100,  101,   77,  100,  101,   97,  100,  101,   78,
      100,  101,   88,  100,  101,   43,  101,   44,  101,   47,
      101,   48,  101,   50,  101,   51,  101,   54,  101,   53,
      101,  101,    1,    3,    2,   74,   41,   61,   69,   62,
       40,   59,   67,   57,   68,   58,   39,   42,   46,   60,
       39,   37,   36,   75,   66,   71,   73,   72,   65,   35,

       63,   35,   35,   30,   35,   35,   35,   35,   35,    8,
       35,   35,   35,   35,   35,   35,   12,   35,   35,   35,
       35,   35,   35,   28,   35,   35,   35,   35,   35,   35,
       35,   64,   70,   43,   44,   44,   45,   47,   50,   54,
       38,   56,   55,   31,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   11,   35,   35,   35,   35,   35,
       33,   35,   34,   35,   35,   35,   35,   35,   35,   16,
       35,   35,   35,   54,   54,   35,    5,   35,   35,   35,
       35,   35,   35,   32,   35,    9,   35,   35,   35,   25,
       35,   35,   35,   27,   35,   35,   35,   35,   35,   35,

       35,   35,    4,   35,   18,   35,   17,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   29,   35,   35,   35,
       35,   26,   35,   15,   35,   35,   35,   35,   35,   10,
       35,   35,   35,   35,   13,   35,   24,   35,   14,   35,
       35,    7,   35,   35,   35,   35,   21,   35,   35,    6,
       35,   22,   35,   35,   19,   35,   35,   23,   35,   20,
       35
    } ;

static yyconst short int yy_accept[252] =
    {   0,
        1,    1,    1,    2,    3,    4,    5,    6,    7,    8,
        9,   10,   12,   15,   17,   20,   23,   25,   28,   31,
       34,   36,   39,   42,   45,   48,   51,   54,   57,   60,
       63,   66,   69,   72,   75,   78,   81,   84,   87,   90,
       93,   96,   99,  102,  105,  108,  111,  114,  117,  120,
      123,  126,  129,  132,  135,  138,  141,  144,  147,  150,
      153,  156,  158,  160,  162,  164,  166,  168,  170,  172,
      173,  174,  175,  175,  176,  177,  177,  178,  178,  179,
      180,  181,  181,  182,  182,  183,  184,  185,  186,  187,
      188,  189,  190,  191,  192,  193,  193,  193,  194,  195,

      196,  197,  198,  199,  200,  201,  202,  203,  204,  206,
      207,  208,  209,  210,  212,  213,  214,  215,  216,  217,
      219,  220,  221,  222,  223,  224,  226,  227,  228,  229,
      230,  231,  232,  233,  234,  235,  236,  237,  238,  239,
      240,  241,  241,  241,  241,  241,  241,  241,  242,  243,
      244,  246,  247,  248,  249,  250,  251,  252,  253,  254,
      255,  257,  258,  259,  260,  261,  263,  265,  266,  267,
      268,  269,  270,  272,  273,  274,  275,  276,  276,  276,
      276,  276,  277,  279,  280,  281,  282,  283,  284,  286,
      288,  289,  290,  292,  293,  294,  296,  297,  298,  299,

      300,  301,  302,  303,  303,  303,  303,  303,  305,  307,
      309,  310,  311,  312,  313,  314,  315,  316,  317,  319,
      320,  321,  322,  324,  326,  327,  328,  329,  330,  332,
      333,  334,  335,  337,  339,  341,  342,  344,  345,  346,
      347,  349,  350,  352,  354,  355,  357,  358,  360,  362,
      362
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   24,
       24,   24,   24,   24,   24,   25,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   33,   33,   33,   33,   33,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       35,   36,   37,   38,   34,    1,   39,   40,   41,   42,

       43,   44,   34,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   34,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    3,    1,    1,    4,    1,    1,    1,
        1,    1,    5,    5,    6,    1,    1,    1,    1,    1,
        3,    1,    6,    7,    1,    3,    1,    1,    5,    5,
        6,    6,    6,    5,    7,    7,    7,    7,    7,    7,
        8,    7,    7,    7,    8,    7,    8,    7,    8,    7,
        8,    7,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[268] =
    {   0,
        0,    0,  349,  347,  360,  359,  358,  357,   56,   57,
      359,  487,   67,  487,   73,  329,   72,  487,  325,   69,
       69,  487,  487,  324,   66,  487,   65,   67,   80,   89,
       94,  326,  487,   58,  322,   70,  487,  487,    0,  487,
      487,  321,  293,   41,   72,   64,   71,   70,   79,  296,
       87,  308,   76,  296,   86,  299,  291,  487,   72,  487,
      487,    0,  117,    0,  487,    0,  487,  124,  487,  487,
      138,  487,  155,  161,  487,  138,  487,  114,  487,  487,
      487,  134,  487,  128,  487,  487,  487,  487,  487,  130,
      487,  487,  487,  148,  155,  160,    0,  167,  487,  306,

      487,  487,  487,  304,    0,  487,  291,  288,    0,  274,
      290,  277,  138,    0,  271,  143,  268,  270,  270,    0,
      279,  273,  257,  266,  266,    0,  273,  257,  264,  266,
      256,  150,  487,  487,    0,  180,  181,  487,    0,    0,
      176,  292,  270,  186,    0,  190,    0,    0,  487,  487,
        0,  261,  256,  241,  149,  162,  255,  252,  253,  250,
        0,  242,  250,  238,  235,    0,    0,  242,  241,  225,
      239,  224,    0,  225,  223,  188,  196,  206,  234,  209,
      265,  223,    0,  213,  211,  220,  207,  206,    0,    0,
      209,  207,    0,  204,  202,    0,  200,  200,  199,  212,

      211,  208,  207,  202,  301,  198,  332,    0,    0,    0,
      198,  199,  204,  188,  193,  195,  198,  186,    0,  186,
      179,  190,    0,    0,  173,  170,  170,  181,    0,  169,
      176,  179,    0,    0,    0,  174,    0,  115,  114,   98,
        0,   65,    0,    0,   42,    0,   50,    0,    0,  487,
      376,  384,  392,  400,  408,  416,  420,  428,  436,  444,
      452,  460,  466,  472,  476,  478,  480
    } ;

static yyconst short int yy_def[268] =
    {   0,
      250,    1,  251,  251,  252,  252,  253,  253,  254,  254,
      250,  250,  250,  250,  250,  250,  255,  250,  250,  250,
      256,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  257,  250,
      250,  250,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  250,  250,  250,
      250,  258,  259,  260,  250,  261,  250,  262,  250,  250,
      250,  250,  250,  250,  250,  255,  250,  263,  250,  250,
      250,  256,  250,  264,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  265,  250,  250,  250,

      250,  250,  250,  250,  257,  250,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  250,  250,  258,  259,  259,  250,  260,  261,
      262,  250,  250,  255,  266,  256,  267,  265,  250,  250,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  262,  262,  255,  255,  256,
      256,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,

      257,  257,  257,  255,  255,  256,  256,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,    0,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250
    } ;

static yyconst short int yy_nxt[554] =
    {   0,
       12,   13,   14,   15,   15,   15,   13,   16,   17,   18,
       12,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   39,   40,   12,   41,   42,   43,   44,
       45,   46,   47,   48,   39,   49,   50,   39,   39,   51,
       52,   53,   39,   39,   54,   55,   39,   39,   56,   57,
       39,   39,   58,   59,   60,   61,   69,   69,   71,   72,
       73,   73,   73,   71,   73,   72,   74,   74,   74,   73,
       77,   80,   83,   86,   88,  100,  101,   70,   70,   90,
       90,   90,  249,   89,   87,  108,   91,   81,  103,  104,

      133,   92,  109,  248,   84,  247,  113,   78,   93,   94,
      110,   95,   95,   96,   94,  114,   98,   98,   98,  115,
      111,  117,  120,  112,  118,  123,  126,  119,  129,  121,
      127,  116,  124,  137,  142,  134,  144,  144,  138,   71,
       72,   73,   73,   73,   71,  130,   77,   83,  246,   97,
      146,  146,   90,   90,   90,  143,   73,   72,   73,   73,
       73,   73,   73,   72,   74,   74,   74,   73,  245,   84,
       90,   90,   90,   78,  145,   94,  244,   95,   95,   96,
       94,  156,   96,   96,   96,  159,  142,   94,  147,   98,
       98,   98,  174,  157,   77,  175,  250,  137,  250,  160,

      187,  250,  138,   83,  185,  186,  142,  143,  178,  178,
       77,   83,  180,  180,   77,  188,  243,  242,  241,  250,
      240,   78,   83,  239,  238,   84,  237,  250,  204,  204,
      236,  206,  206,   84,  235,  234,  233,   78,  232,  231,
      230,   78,   77,  229,   84,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  205,  205,  205,  217,
      216,  215,  214,  213,  212,  211,  205,  210,  209,   78,
      208,  203,  205,  205,  205,  205,  205,  205,   83,  202,
      201,  200,  199,  198,  197,  196,  195,  207,  207,  207,
      194,  193,  192,  191,  190,  189,  184,  207,  183,  182,

       84,  177,  176,  207,  207,  207,  207,  207,  207,   77,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  205,  205,  205,  158,  155,  154,  153,
      152,  151,  150,  205,  149,  132,   78,  131,  128,  205,
      205,  205,  205,  205,  205,   83,  125,  122,  107,  106,
      102,   99,   85,   79,  207,  207,  207,   75,  250,   67,
       67,   65,   65,   63,  207,   63,  250,   84,  250,  250,
      207,  207,  207,  207,  207,  207,   62,   62,   62,   62,
       62,   62,   62,   62,   64,   64,   64,   64,   64,   64,
       64,   64,   66,   66,   66,   66,   66,   66,   66,   66,

       68,   68,   68,   68,   68,   68,   68,   68,   76,  250,
       76,   76,   76,   76,   76,   76,   82,  250,   82,   82,
       82,   82,   82,   82,  105,  105,  105,  105,  135,  135,
      135,  250,  135,  135,  135,  135,  136,  136,  136,  136,
      136,  136,  136,  136,  139,  250,  139,  139,  139,  139,
      139,  139,  140,  250,  140,  140,  140,  140,  140,  140,
      141,  141,  141,  141,  141,  141,  141,  141,   76,  250,
       76,  250,  250,   76,   82,  250,   82,  250,  250,   82,
      148,  148,  179,  179,  181,  181,   11,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250
    } ;

static yyconst short int yy_chk[554] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,   10,   13,   13,
       13,   13,   13,   13,   15,   15,   15,   15,   15,   15,
       17,   20,   21,   25,   27,   34,   34,    9,   10,   28,
       28,   28,  247,   27,   25,   44,   29,   20,   36,   36,

       59,   29,   44,  245,   21,  242,   46,   17,   29,   30,
       45,   30,   30,   30,   31,   46,   31,   31,   31,   47,
       45,   48,   49,   45,   48,   51,   53,   48,   55,   49,
       53,   47,   51,   63,   68,   59,   78,   78,   63,   71,
       71,   71,   71,   71,   71,   55,   76,   82,  240,   30,
       84,   84,   90,   90,   90,   68,   73,   73,   73,   73,
       73,   73,   74,   74,   74,   74,   74,   74,  239,   82,
       94,   94,   94,   76,   78,   95,  238,   95,   95,   95,
       96,  113,   96,   96,   96,  116,  141,   98,   84,   98,
       98,   98,  132,  113,  144,  132,  136,  137,  176,  116,

      156,  136,  137,  146,  155,  155,  177,  141,  144,  144,
      204,  206,  146,  146,  178,  156,  236,  232,  231,  176,
      230,  144,  180,  228,  227,  146,  226,  177,  178,  178,
      225,  180,  180,  206,  222,  221,  220,  204,  218,  217,
      216,  178,  179,  215,  180,  214,  213,  212,  211,  203,
      202,  201,  200,  199,  198,  197,  179,  179,  179,  195,
      194,  192,  191,  188,  187,  186,  179,  185,  184,  179,
      182,  175,  179,  179,  179,  179,  179,  179,  181,  174,
      172,  171,  170,  169,  168,  165,  164,  181,  181,  181,
      163,  162,  160,  159,  158,  157,  154,  181,  153,  152,

      181,  143,  142,  181,  181,  181,  181,  181,  181,  205,
      131,  130,  129,  128,  127,  125,  124,  123,  122,  121,
      119,  118,  117,  205,  205,  205,  115,  112,  111,  110,
      108,  107,  104,  205,  100,   57,  205,   56,   54,  205,
      205,  205,  205,  205,  205,  207,   52,   50,   43,   42,
       35,   32,   24,   19,  207,  207,  207,   16,   11,    8,
        7,    6,    5,    4,  207,    3,    0,  207,    0,    0,
      207,  207,  207,  207,  207,  207,  251,  251,  251,  251,
      251,  251,  251,  251,  252,  252,  252,  252,  252,  252,
      252,  252,  253,  253,  253,  253,  253,  253,  253,  253,

      254,  254,  254,  254,  254,  254,  254,  254,  255,    0,
      255,  255,  255,  255,  255,  255,  256,    0,  256,  256,
      256,  256,  256,  256,  257,  257,  257,  257,  258,  258,
      258,    0,  258,  258,  258,  258,  259,  259,  259,  259,
      259,  259,  259,  259,  260,    0,  260,  260,  260,  260,
      260,  260,  261,    0,  261,  261,  261,  261,  261,  261,
      262,  262,  262,  262,  262,  262,  262,  262,  263,    0,
      263,    0,    0,  263,  264,    0,  264,    0,    0,  264,
      265,  265,  266,  266,  267,  267,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250
    } ;

#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "scriptc.l"
#define INITIAL 0
#line 2 "scriptc.l"
#include "scriptc_syntax.cpp"
#define comment 1

#define cppcomment 2

#define scriptcomment 3

#define textout 4

#line 597 "scriptc_compiler.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "scriptc.l"


#line 727 "scriptc_compiler.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 487 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 35 "scriptc.l"
{
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "scriptc.l"
{
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "scriptc.l"
{			
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "scriptc.l"
{ return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "scriptc.l"
{ return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "scriptc.l"
{ return(CONTINUE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "scriptc.l"
{ return(DEFAULT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "scriptc.l"
{ return(DO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "scriptc.l"
{ return(ELSE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "scriptc.l"
{ return(EXTERN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "scriptc.l"
{ return(FOR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "scriptc.l"
{ return(IF); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "scriptc.l"
{ return(RETURN); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "scriptc.l"
{ return(SWITCH); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "scriptc.l"
{ return(WHILE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "scriptc.l"
{ return(VAR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "scriptc.l"
{ return(CONSTKEY); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "scriptc.l"
{ return(CLASS); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "scriptc.l"
{ return(FUNCTION); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "scriptc.l"
{ return(NAMESPACE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "scriptc.l"
{ return(INCLUDE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "scriptc.l"
{return(DEFQUERY);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "scriptc.l"
{return(EXECQUERY);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "scriptc.l"
{return(SELECT);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "scriptc.l"
{return(FROM);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "scriptc.l"
{return(WHERE);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "scriptc.l"
{return(JOIN);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "scriptc.l"
{return(ON);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "scriptc.l"
{return(ORDER);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "scriptc.l"
{return(BY);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "scriptc.l"
{return(ASC);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "scriptc.l"
{return(DESC);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "scriptc.l"
{return(MAX);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "scriptc.l"
{return(MIN);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 79 "scriptc.l"
{return(IDENTIFIER);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "scriptc.l"
{return(INTEGERconstant);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "scriptc.l"
{return(OCTALconstant);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "scriptc.l"
{return(HEXconstant);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "scriptc.l"
{return(FLOATINGconstant);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 86 "scriptc.l"
{return(STRING_LITERAL);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "scriptc.l"
{return(STRING_LITERAL);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "scriptc.l"
{BEGIN(comment);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "scriptc.l"
{}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 91 "scriptc.l"
{}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 92 "scriptc.l"
BEGIN(INITIAL);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "scriptc.l"
{BEGIN(cppcomment);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 95 "scriptc.l"
{}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "scriptc.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 98 "scriptc.l"
{BEGIN(scriptcomment);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 99 "scriptc.l"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 100 "scriptc.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "scriptc.l"
{BEGIN(textout);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "scriptc.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "scriptc.l"
{return(TEXTBLOCK);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 106 "scriptc.l"
{ return(RIGHT_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "scriptc.l"
{ return(LEFT_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "scriptc.l"
{ return(ADD_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 "scriptc.l"
{ return(SUB_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 110 "scriptc.l"
{ return(MUL_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 111 "scriptc.l"
{ return(DIV_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 112 "scriptc.l"
{ return(MOD_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 113 "scriptc.l"
{ return(AND_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 114 "scriptc.l"
{ return(XOR_ASSIGN); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 115 "scriptc.l"
{ return(OR_ASSIGN); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 116 "scriptc.l"
{ return(RIGHT_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 117 "scriptc.l"
{ return(LEFT_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 118 "scriptc.l"
{ return(INC_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 119 "scriptc.l"
{ return(DEC_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "scriptc.l"
{ return(AND_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "scriptc.l"
{ return(OR_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "scriptc.l"
{ return(LE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "scriptc.l"
{ return(GE_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "scriptc.l"
{ return(EQ_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 125 "scriptc.l"
{ return(NE_OP); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "scriptc.l"
{ return(CLCL_OP); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 127 "scriptc.l"
{ return(';'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 128 "scriptc.l"
{ return('{'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 129 "scriptc.l"
{ return('}'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 130 "scriptc.l"
{ return(','); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 131 "scriptc.l"
{ return('='); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 132 "scriptc.l"
{ return('('); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 133 "scriptc.l"
{ return(')'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 134 "scriptc.l"
{ return('['); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 135 "scriptc.l"
{ return(']'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 136 "scriptc.l"
{ return('.'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 137 "scriptc.l"
{ return('&'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 138 "scriptc.l"
{ return('!'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 139 "scriptc.l"
{ return('~'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 140 "scriptc.l"
{ return('-'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 141 "scriptc.l"
{ return('+'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 142 "scriptc.l"
{ return('*'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 143 "scriptc.l"
{ return('/'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 144 "scriptc.l"
{ return('%'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 145 "scriptc.l"
{ return('<'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 146 "scriptc.l"
{ return('>'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 147 "scriptc.l"
{ return('^'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 148 "scriptc.l"
{ return('|'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 149 "scriptc.l"
{ return(':'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 150 "scriptc.l"
{ return('?'); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "scriptc.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "scriptc.l"
ECHO;
	YY_BREAK
#line 1326 "scriptc_compiler.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(comment):
			case YY_STATE_EOF(cppcomment):
			case YY_STATE_EOF(scriptcomment):
			case YY_STATE_EOF(textout):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 250);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 154 "scriptc.l"
