
// SDString.h - generated by the SLK parser generator 

#ifndef _SDSTRING_H
#define _SDSTRING_H

namespace DataScript {

char *SDGetSymbolName ( unsigned int   symbol );
char *SDGetProductionName ( unsigned int  production_number );



}

#endif
