
// SDTable.cpp - generated by the SLK parser generator 

#include "SDAction.h"

namespace DataScript {

void
SDAction ::
initialize_table ( void )
{
    Action [ 0 ] = 0;
    Action [ 1 ] = &SDAction::endStatement;
    Action [ 2 ] = &SDAction::pushId;
    Action [ 3 ] = &SDAction::buildOperator;
    Action [ 4 ] = &SDAction::buildFirstTernaryOperator;
    Action [ 5 ] = &SDAction::buildSecondTernaryOperator;
    Action [ 6 ] = &SDAction::beginStatement;
    Action [ 7 ] = &SDAction::beginFunction;
    Action [ 8 ] = &SDAction::endFunction;
    Action [ 9 ] = &SDAction::setFunctionId;
    Action [ 10 ] = &SDAction::markHaveStatement;
    Action [ 11 ] = &SDAction::markHaveExternScript;
    Action [ 12 ] = &SDAction::setExternScript;
    Action [ 13 ] = &SDAction::markParenthesisParam;
    Action [ 14 ] = &SDAction::buildHighOrderFunction;
    Action [ 15 ] = &SDAction::markBracketParam;
    Action [ 16 ] = &SDAction::markPeriodParam;
    Action [ 17 ] = &SDAction::setMemberId;
    Action [ 18 ] = &SDAction::markPeriodParenthesisParam;
    Action [ 19 ] = &SDAction::markPeriodBracketParam;
    Action [ 20 ] = &SDAction::markPeriodBraceParam;
    Action [ 21 ] = &SDAction::pushStr;
    Action [ 22 ] = &SDAction::pushNum;
    Action [ 23 ] = &SDAction::pushTrue;
    Action [ 24 ] = &SDAction::pushFalse;
}


}
