
// SDTable.h - generated by the SLK parser generator 

#ifndef _SDTABLE_H
#define _SDTABLE_H

public:

void    endStatement ( void );
void    pushId ( void );
void    buildOperator ( void );
void    buildFirstTernaryOperator ( void );
void    buildSecondTernaryOperator ( void );
void    beginStatement ( void );
void    beginFunction ( void );
void    endFunction ( void );
void    setFunctionId ( void );
void    markHaveStatement ( void );
void    markHaveExternScript ( void );
void    setExternScript ( void );
void    markParenthesisParam ( void );
void    buildHighOrderFunction ( void );
void    markBracketParam ( void );
void    markPeriodParam ( void );
void    setMemberId ( void );
void    markPeriodParenthesisParam ( void );
void    markPeriodBracketParam ( void );
void    markPeriodBraceParam ( void );
void    pushStr ( void );
void    pushNum ( void );
void    pushTrue ( void );
void    pushFalse ( void );

void    ( SDAction::*Action [ 25 ] ) ( void );

void    initialize_table ( void );
void
execute ( int  number )   { ( this->*Action [ number ] ) (); }

#endif
